### ISSUE TITLE
Using SOFA with Ariadne Graphql Server

### ISSUE THREAD

**Issue by lghamie** [Urigo/SOFA#538]
Hi! I have an Ariadne (python/schema-first) GraphQL Server. I have created the schema manually and imported it to sofa using readfile and     const schema = makeExecutableSchema({ typeDefs, resolvers }).

The problem I find with that is that I haven't found a way to automatically implement the resolvers to call my graphql server. Is that possible?  All the exmaples I found seem to be linked to apollo-server.

Thanks!

**Comment by ardatan** [comment]
First of all, let me correct something SOFA isn't server specific library. It just takes your executable schema then serves it through your express server. So the input is not your server but your schema. That means it never requires a link to apollo server or something else.

Since you're using Python, the only way is to create a proxy GraphQL Schema that sends requests via HTTP or some other protocol .
You can check here for creating remote schemas;
https://www.graphql-tools.com/docs/remote-schemas

**Comment by ardatan** [comment]
Feel free to create an new issue if you have any questions and problems while implementing this.
